# Generated by Django 4.2.9 on 2024-08-01 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('fr_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('is_rejected', models.BooleanField(blank=True, default=False, null=True)),
                ('is_accepted8', models.BooleanField(blank=True, default=False, null=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receiver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver_id', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_sender_id', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FriendRequest',
                'db_table': 'friend_request',
            },
        ),
    ]
