# Generated by Django 4.2.9 on 2024-08-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='is_accepted8',
            new_name='is_accepted',
        ),
    ]
